### ISSUE TITLE
Multiplexer value consisting a ":" is interpreted differently

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1296]
Having a multiplex file as follows.
```
PCI_devices: !mux
    pci_device1:
        pci_device: 0002:02:00.0
    pci_device2:
        pci_device: 0001:00:01.1

```
Multiplex tree representation is as below.
```
\-- run
      \-- PCI_devices
           #== pci_device1
           #      -> pci_device: 7320.0
           #== pci_device2
                  -> pci_device: 3601.1

```

**Comment by ldoktor** [comment]
Hello @narasimhan-v, this is the standard yaml behavior as it tries to detect the type of the argument and apparently this matches the `datetime` format. You need to explicitly say it's string by `"`, `'` or making it block of code:

```yaml
PCI_devices: !mux
    pci_device1:
        pci_device: "0002:02:00.0"
    pci_device2:
        pci_device: |
            0001:00:01.1
```
