### ISSUE TITLE
Error printed using variants after upgrading from 49.0 to 52.0

### ISSUE THREAD

**Issue by UnitasBrooks** [avocado-framework/avocado#2123]
Hello,

I upgraded to 52.0 LTS,  got everything working with it except it prints a strange error when grabbing a yaml varianter file:

```
jobdata.variants: Unable to serialize '/expected: track=1, key=frame_rate, value=29.970'
jobdata.variants: Unable to serialize '/expected: track=481, key=height, value=720'
jobdata.variants: Unable to serialize '/expected: track=Video, key=width, value=1280'
```

The interesting thing is that the variants file does seem to get "muxed" correctly and the parameters are passed onto the test.

Here is the yml file:
[mediainfo_test.yml.txt](https://github.com/avocado-framework/avocado/files/1191617/mediainfo_test.yml.txt)

**Comment by apahim** [comment]
This is related to the job data recorder. That recorded data is further used by features like Job Replay and Job diff. If you're not using those features, I don't expect anything else to be broken. I will take a look asap (a.k.a. "probably tomorrow").

**Comment by UnitasBrooks** [comment]
yea it's not effecting too much but I'd like the spammy message to go away before upgrading to 52.0. If there is a way to suppress it that works as well.

**Comment by apahim** [comment]
Despite the messages, is this yaml file working for you? It seems really broken...It creates only one variant, with a list as the value for the parameter `validators`:

```
$ avocado variants -m ~/avocado/tests/mediainfo_test.yml -c
Multiplex variants (1):

Variant some_test_name-3223:    /run/tests/some_test_name
    /run/tests/some_test_name:json       => example2.json
    /run/tests/some_test_name:validators => [[('type', 'MediaInfoValidator'), ('output', '/mnt/big_buck_bunny.mts'), ('check', 'validate_media_info'), MuxTreeNode(name='expected')], [('type', 'MediaInfoValidator'), ('output', '/mnt/big_buck_bunny.mts'), ('check', 'validate_media_info'), MuxTreeNode(name='expected')], [('type', 'MediaInfoValidator'), ('output', '/mnt/big_buck_bunny.mts'), ('check', 'validate_media_info'), MuxTreeNode(name='expected')]]
```

My guess is that you want a file more like this:
```yaml
tests: !mux
    some_test_name:
        json: example.json
        validators: !mux
            validator1:
                type: MediaInfoValidator
                output: /mnt/big_buck_bunny.mts
                check: validate_media_info
                track: 1
                key: frame_rate
                expected_value: "29.970"
            validator2:
                type: MediaInfoValidator
                output: /mnt/big_buck_bunny.mts
                check: validate_media_info
                track: 481
                key: frame_rate
                expected_value: "720"
    some_other_test:
        json: example2.json
        validators: !mux
            validator1:
                type: MediaInfoValidator
                output: /mnt/big_buck_bunny.mts
                check: validate_media_info
                expected:
                track: Video
                key: width
                expected_value: "1280"
```
That would generate the following variants:
```
$ avocado variants -m ~/avocado/tests/mediainfo_test.yml -c
Multiplex variants (3):

Variant validator1-73e2:    /run/tests/some_test_name/validators/validator1
    /run/tests/some_test_name/validators/validator1:check          => validate_media_info
    /run/tests/some_test_name/validators/validator1:expected_value => 29.970
    /run/tests/some_test_name/validators/validator1:key            => frame_rate
    /run/tests/some_test_name/validators/validator1:output         => /mnt/big_buck_bunny.mts
    /run/tests/some_test_name/validators/validator1:track          => 1
    /run/tests/some_test_name/validators/validator1:type           => MediaInfoValidator
    /run/tests/some_test_name:json                                 => example.json

Variant validator2-eb5a:    /run/tests/some_test_name/validators/validator2
    /run/tests/some_test_name/validators/validator2:check          => validate_media_info
    /run/tests/some_test_name/validators/validator2:expected_value => 720
    /run/tests/some_test_name/validators/validator2:key            => frame_rate
    /run/tests/some_test_name/validators/validator2:output         => /mnt/big_buck_bunny.mts
    /run/tests/some_test_name/validators/validator2:track          => 481
    /run/tests/some_test_name/validators/validator2:type           => MediaInfoValidator
    /run/tests/some_test_name:json                                 => example.json

Variant expected-4a6f:    /run/tests/some_other_test/validators/validator1/expected
    /run/tests/some_other_test/validators/validator1:check          => validate_media_info
    /run/tests/some_other_test/validators/validator1:expected_value => 1280
    /run/tests/some_other_test/validators/validator1:key            => width
    /run/tests/some_other_test/validators/validator1:output         => /mnt/big_buck_bunny.mts
    /run/tests/some_other_test/validators/validator1:track          => Video
    /run/tests/some_other_test/validators/validator1:type           => MediaInfoValidator
    /run/tests/some_other_test:json                                 => example2.json
```

Anyway, the fact that we are running the test with that yaml but failing to serialize/record it shows that we have an issue in the jobdata code. I'm creating a Trello card for that.

**Comment by UnitasBrooks** [comment]
Arrays of dictionaries seem to be supported through YAML in my internet searches, it seems unpleasant to create a name for something that is really an index.

**Comment by apahim** [comment]
Yes, they are supported. Issue is in our (new) serialization code.
As for the "seems really broken" comment, for a moment I thought you'd be intending to have each variant with one set of parameters, not all of them in one variant only. You can disregard my yaml suggestion, it makes no sense if my assumption was wrong.

**Comment by apahim** [comment]
https://trello.com/c/sGlqsLd7/1088-bug-jobdatavariants-unable-to-serialize

**Comment by ldoktor** [comment]
Hello @UnitasBrooks, the main problem is that Avocado turns every dictionary into an OrderedDict and then into TreeNode object. This is expected when specifying the namespace (the `/tests/some_test_name`) but it should not be done when producing the actual values, which is the case of the values inside the `validators` list. So far we have neglected this as one can access those values if they cope with the limitations (which is it's node and not dict) but the variants serialization does not reflect that.

We have 3 options I see:

1. you can modify your yaml file(s) to produce the correct values, which means force-tagging objects that are suppose to be dicts as dicts:

```yaml
tests: !mux
    some_test_name:
      json: example2.json
      validators:
        -
          !!python/dict
          type: MediaInfoValidator
          output: /mnt/big_buck_bunny.mts
          check: validate_media_info
          expected:
            !!python/dict
            track: 1
            key: frame_rate
            value: "29.970"
        -
          !!python/dict
          type: MediaInfoValidator
          output: /mnt/big_buck_bunny.mts
          check: validate_media_info
          expected:
            !!python/dict
            track: 481
            key: height
            value: "720"
        -
          !!python/dict
          type: MediaInfoValidator
          output: /mnt/big_buck_bunny.mts
          check: validate_media_info
          expected:
            !!python/dict
            track: Video
            key: width
            value: "1280"
```

2. we/you can (don't know the costs/necessary_time_to_develop yet) modify the avocado yaml loader to only turn dicts connected to root into TreeNodes, therefor dicts behind list would be preserved as dicts.

3. we can modify the serializer to cope with this as demonstrated by Amador, but unless I'm wrong it still needs some work on the de-serialization part (to produce the same values during `--reply` or `diff`).

As dicts are described in documentation as TreeNodes I'd ideally like to use solution (1), but please let me know whether it's acceptable to you. If so we'll improve our documentation to emphasize the need for the `!!python/dict` in rare cases like yours.

**Comment by UnitasBrooks** [comment]
So here is why I don't like !!python/dict, I'm not sure how many other people are using the JSON, but !mux causes json parsing to fail unless you remove it ahead of time. If for instance I wanted to create a UI that generates test configs (mux yml/json) having to deal with generating invalid JSON is a huge pain. Not sure if this is a consideration for other people.

I'm a little confused still, I do get the correct parameters for my test, albeit the nested dictionaries are MuxTreeNodes instead of dictionaries. 

I've already written the code to convert the MuxTreeNode into a python dict, I'm going to find out if I can share it with you today.

**Comment by ldoktor** [comment]
Well the JSON parsing is just a consequence of PyYAML being able to de-serialize it. It's not capable of storing custom tags (not 100% sure about that) so the `!mux` and perhaps the `!!python` tags are and can't be not supported. Why do you need to generate JSON files in the first place? Do you only need single variants? If so we intend to include simple params plugin to be able to inject just params (without variants) which should not be dependent on PyYAML and should be core plugin/part of Avocado (something like `--params $FILE`). The current plan is to go with INI-like format, which should not have the problem with dict vs. node (as in INI one defines namespace and then key+value, so we'd not have to detect whether the dict is namespace, or node). Would that help you?

As I said, I know the current solution where even dicts inside lists are converted to tree-nodes (also dicts inside any other custom object, etc..) is not optimal, but it'd require double-pass to discover which ones are suppose to be dicts so I don't like it much and the `!!python` tag looks better to me. @apahim, @clebergnu what is your opinion on this? Or do you think we should send an email to avocado-devel to get opinion of the wider audience?

I have to say I really dislike the solution (3) as it requires to access the values "differently", therefor the only clean solutions I see are (1) or (2) where (1) requires some knowledge of advanced users and gives single-pass performance and (2) should just work without any additional knowledge (apart the fact that you can't query for dict, because dict becomes a namespace).

**Comment by UnitasBrooks** [comment]
**Why do you need to generate JSON files in the first place?**

To make tests using a common avocado python test file quick to write we've considered creating a UI to generate them.

**Do you only need single variants?**

For right now, although I am pretty excited about the multidimensional variants for doing thinks like performance testing.

**Would a simple --params solution work?**
If it can still iterate and "create tests" like:

```
test_1:
    dict_1:
        key: value
        key: value
    dict_2:
        key: value
test_2:
    dict_1:
        key: value
    dict_2:
        key: value
```

It's possible I'm stretching what the variants were made for, possibly I could create a plugin that better suits my needs. In the mean time while, it involves a bit of explaining the !!python/dict solution is working. Here is how I'm converting the nodes into python dicts:
```
    def __convert_parameters_to_dict(validator_parameters):
        """
        Due to how avocado parses lists we need to convert it to a more digestible format
        :param validator_parameters: usually a list of tuples with a random object bomb shell
        :return: the same list of tuples but in the format of a dictionary
        """
        non_conformant_objects = [check for check in validator_parameters if not
                                    (isinstance(check, Value) or isinstance(check, MuxTreeNode))]

        if len(non_conformant_objects) > 0:
            raise ValueError(
                'Found non MuxTreeNode or non yaml_to_mux.Value in validator parameters passed in from test config')

        tuples = [val for val in validator_parameters if isinstance(val, Value)]
        mux_nodes = [val for val in validator_parameters if isinstance(val, MuxTreeNode)]

        tuple_dict = dict(tuples)
        mux_dict = {val.__dict__['name']: val.__dict__['value'] for val in mux_nodes}

        mux_copy = mux_dict.copy()
        tuple_dict.update(mux_copy)
        
        return tuple_dict
```

**Comment by ldoktor** [comment]
Dne 13.8.2017 v 22:30 Joseph Yuhas napsal(a):
> **Why do you need to generate JSON files in the first place?**
> 
> To make tests using a common avocado python test file quick to write we've considered creating a UI to generate them.

Well can't your UI generate YAML files instead?

Also I'm not sure whether this means test variants, or just some per-test-data.

> 
> **Do you only need single variants?**
> 
> For right now, although I am pretty excited about the multidimensional variants for doing thinks like performance testing.
> 
> **Would a simple --params solution work?**
> If it can still iterate and "create tests" like:
> 
> ```
> test_1:
>     dict_1:
>         key: value
>         key: value
>     dict_2:
>         key: value
> test_2:
>     dict_1:
>         key: value
>     dict_2:
>         key: value
> ```

This made me even more confused. Basically the current params handling system allows only to share the same params between all tests. People were abusing params by injecting params for some tests into specific locations like you demonstrated here, but that is not really correct. Tests should really obtain the values directly from their values and not to look for some magical keyword.

To address this we recently added https://github.com/avocado-framework/avocado/pull/2126 which should allow assigning tests to variants which should assign params to each test:

```yaml
!mux
test_1:
    test_reference: "test1.py"
    !inject : test_1.json
test_2:
    test_reference: "test2.sh"
    !inject : test_2.yaml
```

which results in `/test_2` being inaccessible form test1.

> 
> It's possible I'm stretching what the variants were made for, possibly I could create a plugin that better suits my needs. In the mean time while, it involves a bit of explaining the !!python/dict solution is working. Here is how I'm converting the nodes into python dicts:
> ```
>     def __convert_parameters_to_dict(validator_parameters):
>         """
>         Due to how avocado parses lists we need to convert it to a more digestible format
>         :param validator_parameters: usually a list of tuples with a random object bomb shell
>         :return: the same list of tuples but in the format of a dictionary
>         """
>         non_conformant_objects = [check for check in validator_parameters if not
>                                     (isinstance(check, Value) or isinstance(check, MuxTreeNode))]
> 
>         if len(non_conformant_objects) > 0:
>             raise ValueError(
>                 'Found non MuxTreeNode or non yaml_to_mux.Value in validator parameters passed in from test config')
> 
>         tuples = [val for val in validator_parameters if isinstance(val, Value)]
>         mux_nodes = [val for val in validator_parameters if isinstance(val, MuxTreeNode)]
> 
>         tuple_dict = dict(tuples)
>         mux_dict = {val.__dict__['name']: val.__dict__['value'] for val in mux_nodes}
> 
>         mux_copy = mux_dict.copy()
>         tuple_dict.update(mux_copy)
>         
>         return tuple_dict
> ```
> 

Sure, this works for you as you only use dicts inside a list, but in general one can use dict inside class etc. which makes this a bit tricky. What I don't understand is why are you so strictly against the `!!python/dict` tag, which explicitly tells it to use dictionary.

Anyway I'll cook the dict-like approach and see how it impacts performance. Hopefully it won't be that bad.
Lukáš
