### ISSUE TITLE
Running a test with args?

### ISSUE THREAD

**Issue by kryptek** [avocado-framework/avocado#2279]
The binaries I'm running for my test require specific args to be passed in but it doesn't seem like this is supported (I'm trying this with the remote runner). Is there a work around or can someone point me in the direction of where I would need to look to add this functionality?

**Comment by apahim** [comment]
The syntax `avocado run "my_binary arg1 arg2"` is not supported because Avocado cannot differentiate an argument from a second test. And if you escape the whitespace, Avocado cannot differentiate the argument from the continuation of the test name, if the test name contains a white-space. Anyway, there are some supported ways to run a test with arguments.

- Option 1: Create an instrumented test which executes your binary with the required arguments:

```python
from avocado import Test
from avocado.utils import process

class MyTest(self):

    def test(self):
        cmd = 'my_binary arg1 arg2'
        process.run(cmd)
```

- Option 2: Use the Avocado parameters system and get the parameter inside your test accessing the environment variables Avocado creates (this would require you to edit the source code of your binary.. not the best option, I guess):

```yaml
$ cat params.yaml
arg1: foo
arg2: bar
```

```bash
$ cat test.sh
echo ${arg1}
echo ${arg2}
```
Run with:
```bash
$ avocado run test.sh -m params.yaml
```

- Option 3: Consider your binary an "external runner" and the arguments "avocado tests":

```bash
~$ avocado run 1 2 3 4 5 --external-runner /bin/sleep
JOB ID     : d21bea8b26c3efa17dabc1d72040b282bb7372f0
JOB LOG    : /home/apahim/avocado/job-results/job-2017-11-01T09.21-d21bea8/job.log
 (1/5) 1: PASS (1.11 s)
 (2/5) 2: PASS (2.03 s)
 (3/5) 3: PASS (3.03 s)
 (4/5) 4: PASS (4.03 s)
 (5/5) 5: PASS (5.02 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 16.61 s
JOB HTML   : /home/apahim/avocado/job-results/job-2017-11-01T09.21-d21bea8/results.html
```
---
apahim

**Comment by ldoktor** [comment]
Option three would be `--external-runner` where list of tests is actually list of arguments to the external runner. For example:

```
avocado --show all run --external-runner "/bin/echo" -- "foo" "multiple arugments" "-ne foo\\\nbar\\\nbaz"
```

anyway the external-runner is not supported together with remote-runner so you can only do that locally. 

Would one of suggested solution work for you, or is there something we can do to improve your situation?

**Comment by ldoktor** [comment]
Actually there is fourth solution and that is `yaml_loader`. You can create test-definition file (`tests.yaml`):

```yaml
!mux
# Use ExternalLoader everywhere
test_reference_resolver_class: "avocado.core.loader.ExternalLoader"
# Using echo command
external_echo:
    test_reference: "external_echo"
    # Set the loader_option to "/bin/echo"
    test_reference_resolver_extra:
        !!python/dict
        loader_options: "/bin/echo"
# Using shell
external_shell: !mux
    test_reference: "'exit -1'"
    test_reference_resolver_extra:
        !!python/dict
        loader_options: "/bin/sh -c"
```

and run it using `avocado run -- tests.yaml`:

```
JOB ID     : 685c2e9aef74858afccc058adada950396deebfd
JOB LOG    : /home/medic/avocado/job-results/job-2017-11-01T14.32-685c2e9/job.log
 (1/2) external_echo;external_echo-472b: PASS (0.02 s)
 (2/2) 'exit -1';external_shell-085b: FAIL (0.04 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.32 s
JOB HTML   : /home/medic/avocado/job-results/job-2017-11-01T14.32-685c2e9/results.html
```

Which works with remote runner as well (remember, you need to pass the `tests.yaml` to the remote machine yourself).
