### ISSUE TITLE
not getting all name from yaml when test run

### ISSUE THREAD

**Issue by smruti77** [avocado-framework/avocado#3615]
for example;
```bonding_mode: !mux
    round_robin:
        bonding_mode: "0"
        igmp: !mux
            igmp1:
                resend_igmp: "1"
            igmp_max:
                resend_igmp: "255"
        packets_per_slave: !mux
            packets_random:
                packets_per_slave: "0"
            packets_default:
                packets_per_slave: "1"
                                                        ```
here we are not getting the name "round_robin" in test.
its coming like this how to resolved this problem.
(001/288) bonding.py:Bonding.test_setup;igmp1-packets_random-8905: CANCEL: Test cancelled due to --dry-run (0.01 s)

**Comment by narasimhan-v** [comment]
This is the difference
@clebergnu Is this expected ?
Is there any way we can get all multiplexed values to be displayed ?

```
bonding_mode: !mux
    round-robin:
        bonding_mode: "0"
```
```
(1/1) pass.py:Ioping.test;round-robin-9076: CANCEL: Test cancelled due to --dry-run (0.00 s)
```


```
bonding_mode: !mux
    round-robin:
        bonding_mode: "0"
        igmp: !mux
            igmp_min:
                resend_igmp: "1"
            igmp_max:
                resend_igmp: "255"
        packets_per_slave: !mux
            packets_random:
                packets_per_slave: "0"
            packets_default:
                packets_per_slave: "1"
```
```
 (1/4) pass.py:Ioping.test;igmp_min-packets_random-96c5: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/4) pass.py:Ioping.test;igmp_min-packets_default-c498: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (3/4) pass.py:Ioping.test;igmp_max-packets_random-99b6: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (4/4) pass.py:Ioping.test;igmp_max-packets_default-9f2e: CANCEL: Test cancelled due to --dry-run (0.00 s)
```

**Comment by PraveenPenguin** [comment]
> bonding_mode

@narasimhan-v I think it expected let we get @clebergnu thought as well

**Comment by apahim** [comment]
https://github.com/avocado-framework/avocado/blob/master/avocado/core/varianter.py#L50

**Comment by narasimhan-v** [comment]
@apahim Right, can we have a way to get even non-leaf multiplexed node to be displayed ?

**Comment by narasimhan-v** [comment]
Without that, this will happen:

```
bonding_mode: !mux
    round-robin:
        bonding_mode: "0"
        igmp: !mux
            igmp_min:
                resend_igmp: "1"
            igmp_max:
                resend_igmp: "255"
        packets_per_slave: !mux
            packets_random:
                packets_per_slave: "0"
            packets_default:
                packets_per_slave: "1"
    active-backup:
        bonding_mode: "1"
        igmp: !mux
            igmp_min:
                resend_igmp: "1"
            igmp_max:
                resend_igmp: "255"
        packets_per_slave: !mux
            packets_random:
                packets_per_slave: "0"
            packets_default:
                packets_per_slave: "1"
```
```
JOB ID     : 0000000000000000000000000000000000000000
JOB LOG    : /var/tmp/avocado-dry-run-dt5k919n/job-2020-03-02T23.15-0000000/job.log
 (1/8) pass.py:Ioping.test;igmp_min-packets_random-96c5: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (2/8) pass.py:Ioping.test;igmp_min-packets_default-c498: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (3/8) pass.py:Ioping.test;igmp_max-packets_random-99b6: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (4/8) pass.py:Ioping.test;igmp_max-packets_default-9f2e: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (5/8) pass.py:Ioping.test;igmp_min-packets_random-ee26: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (6/8) pass.py:Ioping.test;igmp_min-packets_default-91c2: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (7/8) pass.py:Ioping.test;igmp_max-packets_random-4e03: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (8/8) pass.py:Ioping.test;igmp_max-packets_default-83b5: CANCEL: Test cancelled due to --dry-run (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 8
JOB TIME   : 1.17 s
```
