### ISSUE TITLE
selftests/signedoff-check.sh false positive on GH Actions CI job

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5670]
**Describe the bug**
A commit without a `Signed-off-by` can result in a successful pass when checked with `selftests/signedoff-check.sh` on GH Actions.

**Steps to reproduce**
Send a PR with a commit without a `Signed-off-by` line and let the CI jobs run.

One example is [here](https://github.com/avocado-framework/avocado/actions/runs/4762040395/jobs/8591248619?pr=5653#step:8:22).

**Expected behavior**
Commits without `Signed-off-by` line should trigger a failure, no matter where they are run.

**Current behavior**
The test passes on GH Actions CI Jobs, but fails at my local system.

**System information (please complete the following information):**
 - OS: `LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven`
 - Avocado version: `a8e630e03cbc923cf4c0dcb84171db0d5fa67ac3` from https://github.com/avocado-framework/avocado/pull/5653
 - Avocado installation method: `make develop`

**Additional information**
Add any other information about the problem here. Test details can be added here.

**Comment by richtja** [comment]
Hi @clebergnu, I did a couple of tests on [GH Actions](https://github.com/richtja/avocado/actions/workflows/ci.yml) and I am unable to reproduce this. It looks like `signedoff-check.sh` works correctly in GH Actions.

**Comment by PaulYuuu** [comment]
Currently, the checkout step is:
```
jobs:
  static-checks:

    name: Static checks
    runs-on: ubuntu-20.04
    container:
      image: quay.io/avocado-framework/avocado-ci-fedora-36

    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event on branch is ${{ github.ref }} in repository is ${{ github.repository }}, runner on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

I also meet a similar issue, please see: https://github.com/autotest/tp-qemu/pull/3668#discussion_r1188058524, finally I add `ref: ${{ github.event.pull_request.head.sha }}`. Without this, the git operation is "git rebase", with this, it's "git merge" I guess.

So if the commit date is too old, and we have some commits merged after that commit date, the latest commit is not the patch commit. Just share some info, you can have a try.

BTW, if the PR contains more than 1 commit, the current CI check only check the last one. This is addressed in tp-qemu: https://github.com/autotest/tp-qemu/pull/3668, which also includes some other checks.
