### ISSUE TITLE
Filtering Specific Variants with `--mux-filter-only` Includes Unrelated Variants

### ISSUE THREAD

**Issue by Moghees244** [avocado-framework/avocado#6084]
**Bug Description**  
Filtering specific variants using `--mux-filter-only` does not work as expected. When attempting to filter for a single variant (e.g., `/run/qemu-guests/kali`), additional unrelated variants are also included in the output.

---

**Steps to reproduce**  
1. Create a `test_params.yaml` file with the following structure:  
   ```yaml
   !mux
   qemu:
       remote_host: "127.0.0.1"
       remote_ssh_port: "2222"
       user: "root"

   qemu-guests: !mux
       kali:
           remote_host: "127.0.0.1"
           remote_ssh_port: "2223"
           user: "root"
           domain_name: "kali"

       ewaol:
           remote_host: "127.0.0.1"
           remote_ssh_port: "2224"
           user: "root"
           domain_name: "ewaol"
   ```  
2. Run the following commands to generate and filter variants:  
   - `avocado variants --mux-yaml test_params.yaml --mux-filter-only /run/qemu-guests`  
   - `avocado variants --mux-yaml test_params.yaml --mux-filter-only /run/qemu-guests/kali`

---

**Expected behavior**  
The command `avocado variants --mux-yaml test_params.yaml --mux-filter-only /run/qemu-guests/kali` should return only the `kali` variant and exclude other unrelated variants like `ewaol`.

---

**Current behavior**  
The command returns multiple variants instead of only the specified one. Example output:  
```
Multiplex variants (2):
Variant run-qemu-3ec6:    /run/qemu
Variant run-qemu-guests-kali-68b9:    /run/qemu-guests/kali
```

---

**System information**  
- **OS:** Output of `lsb_release -a`:  
  ```  
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 22.04.4 LTS
  Release:        22.04
  Codename:       jammy
  ```  
- **Avocado version:** Output of `avocado -v`:  
  ```
  Avocado 108.0  
  ```  
- **Avocado installation method:**
  ```
  git clone https://github.com/avocado-framework/avocado
  pip install avocado-framework
  ```

---

**Comment by Moghees244** [comment]
As I have mentioned, this is the expected behaviour. Please check current
behaviour heading.

I am using /run/qemu-guests/kali filter
but it is still running /run/qemu

**Comment by Moghees244** [comment]
Hi @richtja . There's still this issue:

```yaml
qemu: !mux
    remote_host: "127.0.0.1"
    remote_ssh_port: "2222"
    user: "root"

qemu-guests: !mux
    kali:
        remote_host: "127.0.0.1"
        remote_ssh_port: "2223"
        user: "root"
        domain_name: "kali"

    ewaol:
        remote_host: "127.0.0.1"
        remote_ssh_port: "2224"
        user: "root"
        domain_name: "ewaol"
```


```shell
avocado variants --mux-yaml params.yaml --mux-filter-only /run/qemu-guests/kali
Multiplex variants (1):
Variant run-qemu-qemu-guests-kali-9a12:    /run/qemu, /run/qemu-guests/kali


avocado run test.py --mux-yaml params.yaml --mux-filter-only /run/qemu-guests/kali
JOB ID     : 21939080dd834ef05c4445bd832b321ac80a5833
JOB LOG    : /root/avocado/job-results/job-2025-01-03T12.17-2193908/job.log
 (1/2) test.py:TestKVMGuestsAccess.test_guest_ip_addr;run-qemu-qemu-guests-kali-9a12: STARTED
 (2/2) test.py:TestKVMGuestsAccess.test_guest_ssh_connection;run-qemu-qemu-guests-kali-9a12: STARTED
 (1/2) test.py:TestKVMGuestsAccess.test_guest_ip_addr;run-qemu-qemu-guests-kali-9a12: ERROR: Multiple  leaves contain the key 'remote_host'; ['/run/qemu=>127.0.0.1', '/run/qemu-guests/kali=>127.0.0.1'] (0.02 s)
 (2/2) test.py:TestKVMGuestsAccess.test_guest_ssh_connection;run-qemu-qemu-guests-kali-9a12: ERROR: Multiple  leaves contain the key 'remote_host'; ['/run/qemu=>127.0.0.1', '/run/qemu-guests/kali=>127.0.0.1'] (0.02 s)
RESULTS    : PASS 0 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2025-01-03T12.17-2193908/results.html
JOB TIME   : 1.60 s
````
